name: NovaCore
version: '1.0-SNAPSHOT'
main: me.sharp.novaCore.NovaCore
api-version: '1.21'
authors: [vindognz]
description: Core plugin for NovaSMP
commands:
  test:
    description: test command
    usage: /test